name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}f

      - name: Restore
        run: dotnet restore DevHabit.slnx

      - name: Build
        run: dotnet build DevHabit.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test DevHabit.slnx --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish DevHabit.slnx --configuration Release --no-restore --no-build